---
- hosts: webservers
  become: true
  gather_facts: yes
  become_method: sudo

  vars:
    site_name: "application2"
       
  tasks:

  - name: install flask and gunicorn dependencies
    become: true
    apt:
        name: "{{ packages }}"
    vars:
        packages:
        - python3-pip
        - python3-dev
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-setuptools
        - python3-venv 

# create virtual env
  - name: create Python virtual environment
    raw: cd /srv; mkdir {{ site_name }}; cd {{ site_name }}; python3 -m venv {{ site_name }}env

  - name: install pip
    pip:
        name: pip
        state: latest
        virtualenv: /srv/{{ site_name }}/{{ site_name}}env

  - name: set up flask and gunicorn
    pip:
        name: 
          - wheel
          - gunicorn
          - flask
        virtualenv: /srv/{{ site_name }}/{{ site_name}}env


# copy application2.py

  - name: copy code
    template:
        src: application2.py
        dest: "/srv/{{ site_name }}"
#wsgi

  - name: create WSGI 
    template:
        src: wsgi.py
        dest: "/srv/{{ site_name }}"


# service for gunicorn/flask
  - name: service for gunicorn and flask
    template:
        src: myapp.service
        dest: "/etc/systemd/system/"

  - name: restart custom service
    systemd:
        state: restarted
        daemon_reload: yes
        name: myproject.service

#nginx 

  - name: install nginx 
    package: name=nginx state=latest

  - name: create directory
    file: path="/var/www/{{ site_name }}" state=directory mode=0755

  - name: create nginx config file
    template:
        src: nginx.conf
        dest: "/etc/nginx/nginx.conf"
    notify:
      - restart nginx

#nginx 
  - name: Create nginx vhost config file
    template:
        src: myapp.conf
        dest: "/etc/nginx/sites-available/myapp.conf"
    notify:
      - restart nginx

  - name: Create symlinks
    file: src=/etc/nginx/sites-available/myapp.conf dest=/etc/nginx/sites-enabled/myapp.conf state=link
    notify:
      - restart nginx

# removing default file

  - name: also remove default nginx vhost configuration
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify:
      - restart nginx

###### CHANGE

  - name: update cache
    become: true
    apt:
       update_cache: yes

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

# HAPROXY CONFIGURATION

- hosts: HAproxy
  gather_facts: yes
  become: true
  become_method: sudo

  tasks:

  - name: update apt cache
    become: yes
    apt:
      update_cache: yes

  - name: haproxy installation
    become: true
    apt:
      name: haproxy
      state: latest   

  - name: upgrade the packages
    become: true
    apt:
      update_cache: yes
    notify:
        - run Haproxy   

  - name: Gather facts from servers
    setup:
      filter: ansible_default_ipv4.address   


  - name: removing haproxy.cfg
    file:
       path: "/etc/haproxy/haproxy.cfg"
       state: absent
    notify:
     - restart haproxy


  - name: Deploying haproxy.cfg 
    template:
      src: haproxy.cfg.j2
      dest: "/etc/haproxy/haproxy.cfg"
    notify:
      - restart haproxy
      - run Haproxy

  handlers:

  - name: run Haproxy
    service:
        name: haproxy

  - name: restart haproxy
    service:
      name: haproxy
      state: restarted
  



